"apiVersion": "v1"
"clusters":
- "cluster":
    "certificate-authority-data": ""
    "server": ""
  "name": "cluster.local"
"contexts":
- "context":
    "cluster": "cluster.local"
    "user": "master-user"
  "name": "cluster.local"
"current-context": "cluster.local"
"kind": "Config"
"preferences": {}
"users":
- "name": "master-user"
  "user":
    "client-certificate-data": ""
    "client-key-data": ""
